### ISSUE TITLE
How to open the app with notification message

### ISSUE THREAD

**Issue by mjohn123** [Chagall/notification-listener-service-example#1]
Thank you so much for a good job. I want to extend your work as follows:

When an incoming message in the notification bar, we can determine the application name. Based on it, we can launch the app as follows:

```
        String packageName = sbn.getPackageName();
        PackageManager pm = getApplicationContext().getPackageManager();
        Intent launchIntent = pm.getLaunchIntentForPackage(packageName);
```

However, the above code only helps to open the app, instead of open the message directly. I want to automatically open the message of sender. Is it possible? Thank you

**Comment by Chagall** [comment]
Hi @mjohn123 I just saw your message. I am investigating if this is possible right now. As soon as I get an answer I will post it here.

**Comment by Chagall** [comment]
@mjohn123 Hello again! I think I might have found a solution to your problem.

Based on what you said I understood this: You want to get an incoming message (from Facebook or Whatsapp, for example) and automatically open the app to show the received message. Is that it?

If that is what you want to do then you can use the code below to accomplish it:

```
        // Lets say you only want to open the messages from whatsapp, so you will do the following
        public static final String WHATSAPP_PACKAGE_NAME = "com.whatsapp";

        if(WHATSAPP_PACKAGE_NAME.equals(sbn.getPackageName()){
            Notification notification = sbn.getNotification();
            /* 
                Notifications usually have a PendingIntent attached to them. 
                A Pending Intent in this case is used to store the action that should be performed 
                when you open the status bar and click on the notification
             */
            // So we get the pending intent
            PendingIntent pendingIntent = notification.contentIntent;
            // And tell it to try to perform the action that would be performed when you clicked
            // on the notification
            try {
                pendingIntent.send();
            } catch (PendingIntent.CanceledException e) {
                e.printStackTrace();
            }
        }
```

I believe that if you are trying to open the messages from Whatsapp, FacebookMessenger, or similar apps this will work, since the default PendingIntent action for these apps is to open the app on the Activity(Screen) that contains the message (Which I believe is what you want to do).

**Comment by mjohn123** [comment]
Great solution. I used your code and it worked well. Thank you for great solution
