### ISSUE TITLE
Not working in marshmallow?

### ISSUE THREAD

**Issue by x4080** [Chagall/notification-listener-service-example#2]
Hi, I'm importing your project in Android Studio and app work but the notification listener is not working (not getting any notifications)

Is it now not compatible ?

PS, I tried some examples in the web and its not working also

Thanks

**Comment by Chagall** [comment]
Hello @x4080. I did a test on an emulated Google Nexus 5 with Android 6.0 (Marshmallow API 23) and it worked fine for me. See picture below:

![working example](https://cloud.githubusercontent.com/assets/5427155/24266689/7b428542-0fe6-11e7-9c28-562916c9ac8f.png)

Did you remember to go to settings and enable notification access for the app? Because if you don't do that Android doesn`t allow the app. to work.

Also, can you explain in more details which phone you are using, system specs, etc? So that I can try to emulate that.

**Comment by Chagall** [comment]
Make sure that you have followed the steps bellow on Android 6.0 (Marshmallow) before testing the app, otherwise it won't work.

**First:** Go to Settings

![1](https://cloud.githubusercontent.com/assets/5427155/24262553/2bd31f56-0fd9-11e7-9ab0-b2f44f52cbc3.png)

**Second:** Go to Sound & Notification

![2](https://cloud.githubusercontent.com/assets/5427155/24262555/2d4ecbbe-0fd9-11e7-8760-1a8b3ef1225a.png)

**Third:** Go to notification access

![3](https://cloud.githubusercontent.com/assets/5427155/24262561/2ea574b8-0fd9-11e7-872d-b673f86f9e74.png)

**Finally**: Make sure that the switch for Notification Listener Example in **turned ON**

![4](https://cloud.githubusercontent.com/assets/5427155/24262562/300b2c58-0fd9-11e7-8d8a-363830ac0855.png)

**Comment by x4080** [comment]
Hi, I tried it again, and first it works in my app, then I retried your app and it works, I guess there's some bug in the emulator somehow and the code : isNotificationServiceEnabled is important, if I enable it manually, the notification listener is not working but using that code to activate it, it works somehow

Thanks and sorry to bother you
